#!/bin/bash
set -e

PATH=$PATH:/Applications/Xcode.app/Contents/Developer/usr/bin/

VERSION=$(./version)
NAME="DROID Forge"
QT_DIR=~/Qt/6.3.1
PATH=$PATH:$QT_DIR/macos/bin
APP_ICON=droidforge/droidforge.icns
INSTALL_ROOT=droidforge/build/release-mac/install-root/usr/local/Applications
APP_DIR="$INSTALL_ROOT/$NAME.app"
# DMGDIR=dmgbase
DMGNAME="$NAME $VERSION.dmg"
TARGET_INFO_PLIST=$APP_DIR/Contents/Info.plist
# LICENSE="droidforge/GNU GPL v3.txt"
TARGET_LICENSE="$APP_DIR/Contents"
# CERTIDENT=Z8A7223C2C
# CERTIDENT="Developer ID Application: Matthias Kettner"
CERTIDENT="Developer ID Application: Matthias Kettner (Z8A7223C2C)"

# First build the project

echo "Cleaning old build..."
rm -rf "$APP_DIR"
echo "Now do the Release-build in QtCreator and press enter!"
read
echo "Continuing..."


if [ ! -e "$APP_DIR" ] ; then
    echo "$APP_DIR missing. Please build release in Qt creator."
    exit 1
fi

echo -n "Fixing rpath..."
install_name_tool -add_rpath @loader_path/../Frameworks "$APP_DIR/Contents/MacOS/$NAME"
echo OK

echo -n "Installing Info.plist..."
cp -v Info.plist "$TARGET_INFO_PLIST"
echo OK

# echo -m "Installing GPL License..."
# cp -v "$LICENSE" "$TARGET_LICENSE"

echo -n "Installing icon..."
mkdir -p "$APP_DIR/Contents/Resources"
cp -v "$APP_ICON" "$APP_DIR/Contents/Resources"
echo OK

echo -n "Adding all dependencies and sign (with macdeployqt)..."
pushd "$INSTALL_ROOT"
macdeployqt "$NAME.app" -verbose=2 -dmg -hardened-runtime -timestamp -codesign=$CERTIDENT -sign-for-notarization=$CERTIDENT
echo OK
popd

mv -v "$INSTALL_ROOT/$NAME.dmg" "$DMGNAME"

echo -n "Signing DMG"...
codesign -vvv -f --options runtime --timestamp -s "Developer ID" "$DMGNAME"
echo OK

echo -n "Notarizing this thing..."
notarytool submit "$DMGNAME" --keychain-profile "DROIDFORGE" --wait
echo OK

echo -n "Stapling..."
stapler staple "$DMGNAME"
echo OK

