#!/bin/sh
set -e

RELEASE=../mk/modular/droid/releases/latest
cp -v $RELEASE/utilities/editors/circuits.json droidforge/droidfirmware.json
cp -v $RELEASE/manual/droid-manual-*.pdf droidforge/droid-manual.pdf
git rm -rf droidforge/firmware
rm -rf droidforge/firmware
mkdir droidforge/firmware
cp -v $RELEASE/firmware/*.fw droidforge/firmware/
git add droidforge/firmware/*.fw

# # Adapt resources.qrc
#         ...
#         <file>pg/minimal</file>
#         <file>images/circuits/ifequal.png</file>
#         <file>firmware/e4-magenta-1.fw</file>
#         <file>firmware/m4-orange-3.fw</file>
#         <file>firmware/x7-orange-1012.fw</file>
#         <file>firmware/master18-magenta-2.fw</file>
#         <file>firmware/droid-magenta-2.fw</file>
#     </qresource>
# </RCC>

fgrep -v '<file>firmware/' droidforge/resources.qrc | \
  fgrep -v '</qresource>' | \
  fgrep -v '</RCC>' > newres.qrc

for f in $(cd droidforge/firmware ; ls) ; do
    echo "        <file>firmware/$f</file>" >> newres.qrc
done

echo "    </qresource>" >> newres.qrc
echo "</RCC>" >> newres.qrc
mv newres.qrc droidforge/resources.qrc

