#!/bin/bash

# After updating the application icon file "droidforge-icon.png" with Illustrator or any other
# software at a resolution of 1024x1024 pixels, this script creates an ICNS file for Mac.

set -e

TMPDIR=droidforge.iconset
SOURCEPNG=droidforge-icon.png
mkdir $TMPDIR

sips -z 16 16     $SOURCEPNG --out $TMPDIR/icon_16x16.png
sips -z 32 32     $SOURCEPNG --out $TMPDIR/icon_16x16@2x.png
sips -z 32 32     $SOURCEPNG --out $TMPDIR/icon_32x32.png
sips -z 64 64     $SOURCEPNG --out $TMPDIR/icon_32x32@2x.png
sips -z 128 128   $SOURCEPNG --out $TMPDIR/icon_128x128.png
sips -z 256 256   $SOURCEPNG --out $TMPDIR/icon_128x128@2x.png
sips -z 256 256   $SOURCEPNG --out $TMPDIR/icon_256x256.png
sips -z 512 512   $SOURCEPNG --out $TMPDIR/icon_256x256@2x.png
sips -z 512 512   $SOURCEPNG --out $TMPDIR/icon_512x512.png
cp $SOURCEPNG $TMPDIR/icon_512x512@2x.png
iconutil -c icns $TMPDIR
cp -v droidforge.icns droidforge/
rm -R $TMPDIR
