#!/bin/bash

set -e
set -v

VERSION=$(./version)
WORKDIR=deploy-tmp-dir
PACDIR=$(pwd)/winpackbasedir
DATADIR="$PACDIR/packages/de.dmmdm.droidforge/data"
METADIR="$PACDIR/packages/de.dmmdm.droidforge/meta"
BUILDDIR=droidforge/build-release
WINDEPLOYQT="/C/Qt/6.3.1/msvc2019_64/bin/windeployqt.exe"
BINARYCREATOR="/C/Qt/QtIFW-4.4.1/bin/binarycreator.exe"

rm -rf "$WORKDIR"
mkdir -p "$WORKDIR"
cp -v "$BUILDDIR/desktop/install-root/bin/DROID Forge.exe" "$WORKDIR"
cd "$WORKDIR"
$WINDEPLOYQT "DROID Forge.exe"
cd ..

# This was needed when the compiler mingw was used
# cp -v mingwlibs/* "$WORKDIR"


echo "Creating package for Windows in $PACDIR..."
rm -rf "$PACDIR"
mkdir -vp "$DATADIR" "$METADIR" "$PACDIR/config"

cp -prv "$WORKDIR"/* "$DATADIR"
cp "droidforge/GNU GPL v3.txt" "$PACDIR/packages/de.dmmdm.droidforge/meta"



cat <<EOF > "$PACDIR/config/config.xml"
<?xml version="1.0" encoding="UTF-8"?>
<Installer>
    <Name>DROID Forge $VERSION</Name>
    <Version>$VERSION</Version>
    <Title>DROID Forge $VERSION Installer</Title>
    <Publisher>Der Mann mit der Maschine</Publisher>
    <StartMenuDir>DROID Forge</StartMenuDir>
    <TargetDir>@HomeDir@/DROID Forge $VERSION</TargetDir>
</Installer>
EOF

cat << EOF > "$METADIR/package.xml"
<?xml version="1.0" encoding="UTF-8"?>
<Package>
    <DisplayName>DROID Forge $VERSION</DisplayName>
    <Description>Create patches for your DROID master from Der Mann mit der Maschine</Description>
    <Version>$VERSION</Version>
    <ReleaseDate>$(date +%Y-%m-%d)</ReleaseDate>
    <Default>true</Default>
    <Script>installscript.qs</Script>
</Package>
EOF

cat << EOF > "$METADIR/installscript.qs"
function Component()
{
    // default constructor
}

Component.prototype.createOperations = function()
{
    // call default implementation to actually install README.txt!
    component.createOperations();

    if (systemInfo.productType === "windows") {
        component.addOperation("CreateShortcut", "@TargetDir@/DROID Forge.exe", "@StartMenuDir@/DROID Forge.lnk",
            "workingDirectory=@TargetDir@");
    }
}
EOF

cat << EOF > "$PACDIR/README"
Servus.
EOF

cat << EOF > "$PACDIR/droidforge.pro"
TEMPLATE = aux

INSTALLER = installer

INPUT = $$PWD/config/config.xml $$PWD/packages
example.input = INPUT
example.output = $$INSTALLER
example.commands = ../../bin/binarycreator -c $$PWD/config/config.xml -p $$PWD/packages ${QMAKE_FILE_OUT}
example.CONFIG += target_predeps no_link combine

QMAKE_EXTRA_COMPILERS += example

OTHER_FILES = README

win32:RC_ICONS += droidforge-win-icon.ico
EOF


cd "$PACDIR"
$BINARYCREATOR --offline-only --config config/config.xml -p packages ../droid-installer-$VERSION.exe

rm -rf "$WORKDIR" "$PACDIR"

