#include "registertypes.h"

const char register_types[NUM_REGISTER_TYPES] = {
  REGISTER_INPUT,
  REGISTER_NORMALIZE,
  REGISTER_OUTPUT,
  REGISTER_GATE,
  REGISTER_BUTTON,
  REGISTER_LED,
  REGISTER_POT,
  REGISTER_SWITCH,
  REGISTER_RGB,
  REGISTER_EXTRA,
};

